(import (silly-k))

;(debug-passes "foo")
;(debug-passes "foo bar")
(debug-passes "1")
(debug-passes "1 2 3")
;(debug-passes "{w}")
;(debug-passes "{a}")
(debug-passes "{1-w}2")
(debug-passes "{1+w}2 3 4")
(debug-passes "{1+w}'1 2 3")
(debug-passes "{1-w}'1 2 3")
;(debug-passes "{x w w}")
;(debug-passes "{w+{w}}2")
(debug-passes "1+1 2 3")
(debug-passes "1 2+3 4")
(debug-passes "1 2 3+1")
(debug-passes "1{a+w}2")
(debug-passes "1{a+w}2 3 4")
(debug-passes "1-2")
(debug-passes "1+2")
(debug-passes "1+2+3+4")
(debug-passes "1+2-3+4")
(debug-passes "(1:)+0:")
(debug-passes "(0:)+0:")

(debug-passes "-2")
